### ISSUE TITLE
Link to Security issues broken

### ISSUE THREAD

**Issue by orcpac7** [wekan/wekan.github.io#13]
On the page at https://github.com/wekan/wekan/wiki
under the heading:
Security
There is a link whose text reads:
    Security Disclosure and details of Security in Wekan
    which points to:
https://github.com/wekan/wekan/blob/devel/SECURITY.md

Clicking that link results in a 404-Page not found.

**Comment by xet7** [comment]
@orcpac7 

Good catch, thanks a lot !

I did delete devel branch some time ago, Wekan uses master branch currently, so I corrected link to point to master branch.

**Comment by xet7** [comment]
Corrected link is:
https://github.com/wekan/wekan/blob/master/SECURITY.md

**Comment by orcpac7** [comment]
Happy to help!

Tried Wekan on Windows, but ;-{
Loaded it per instructions for running under Windows (not docker or linux)
and couldn't get it going, Tiaga didn't appear to *have* a windows version
so trying Kanboard next.

Happily used Portable Kanban for years, but Dmitri seems to have
disappeared and site no longer up, so looking to migrate to an Open Source
locally hosted board on Windows. *Wekan looked very good but too much
installation confusion to deal with today...*

Regards,

Jeff Davis
(571) 353-4048 mobile

**Comment by xet7** [comment]
@orcpac7 

Windows without Docker info here, option a)
https://github.com/wekan/wekan/wiki/Windows
