### ISSUE TITLE
Websites refinement

### ISSUE THREAD

**Issue by helioguardabaxo** [wekan/wekan.github.io#15]
Hi, @xet7!

I saw in Wekan survey results that a user suggested a refinement in the website.
I were worked in a prototype. You can see bellow:

![Screenshot_2020-07-04 Smash - Bootstrap Business Template(2)](https://user-images.githubusercontent.com/24301085/86523095-ae9c9000-be3d-11ea-9a4e-3f2058e8cb24.png)

![Screenshot_2020-07-04 Smash - Bootstrap Business Template(1)](https://user-images.githubusercontent.com/24301085/86523094-aa707280-be3d-11ea-98ab-6c9a3d6ee4bc.png)

What do you think about it?

I intend to adjust the colors of this template.
I have a drawing friend. I could ask him to create a Kanban board design for the main banner.

**Comment by helioguardabaxo** [comment]
I used this template:
https://onepagelove.com/smash-lite

**Comment by helioguardabaxo** [comment]
I did some changes in "Features" and top menu.

![Screenshot_2020-07-04 Smash - Bootstrap Business Template(4)](https://user-images.githubusercontent.com/24301085/86524138-27efaf00-be4d-11ea-9940-8970c88cf118.png)

**Comment by shtefcs** [comment]
I like it and think it looks much better easier and professional

**Comment by xet7** [comment]
@helioguardabaxo 

Please add pull request to this repo with that new theme.

**Comment by helioguardabaxo** [comment]
I found out that you have a license for personal use:
FOR FREE LITE VERSION:
1. Commercial Use - Not Allowed
2. Removing Footer Credit - Not Allowed
3. Documentation - Not Available
4. Support - Not Provided
6. Personal Projects - Allowed

The commercial license costs $ 15
https://uideck.com/templates/smash/
I can pay for it, no problem.

**Comment by helioguardabaxo** [comment]
alternatively, I could refine the current site

**Comment by xet7** [comment]
@helioguardabaxo 

Please do not use any commercial paid template. All of Wekan if Free Software and Open Source and does not use any paid commercial parts. All parts of Wekan are free to use also for commercial use, without any payments.

It's not necessary for website to look like those of big faceless bit tech corporations.

Currently all of Wekan is Open Source. There is nothing propietary, and there is no separate Enterprise version.

**Comment by Chralf** [comment]
I have pushed som changes. Only with Open Source.

<img width="690" alt="bild" src="https://user-images.githubusercontent.com/126474697/222928515-43aed785-fa7f-4c88-b4db-a963d630c00a.png">

**Comment by xet7** [comment]
@Chralf 

That looks great !

Can you make pull request?

1. Like at https://github.com/wekan/wekan/wiki/Emoji
2. Create fork of repo https://github.com/wekan/wekan.github.io with GitHub fork button
3. Then clone website:

```
git clone git@github.com:Chralf/wekan.github.io

cd wekan.github.io
```

4. Make changes to files.
5. Commit and push:

```
git add --all

git commit -m "New layout"

git push
```

6. Then at https://github.com/Chralf/wekan.github.io click "Create pull request"

**Comment by Chralf** [comment]
If this works its my first push of code on Github. Hope I did it right.

**Comment by xet7** [comment]
To get newest changes to your fork, it's possible to do this, it also updates your fork:
```
cd wekan.github.io

git remote add upstream https://github.com/wekan/wekan.github.io

git fetch upstream

git merge upstream/master

git push
```
If it starts nano text editor sometime, it's possible to save and exit with: Ctrl-o Enter Ctrl-x Enter

After upstream repo has been added, it does not need to be added next time.

Other way is to delete your fork and make new fork of wekan.github.io repo etc.
