### ISSUE TITLE
Broken Link on main page

### ISSUE THREAD

**Issue by Tanarri** [wekan/wekan.github.io#26]
Hi,

there are 2 broken links at the end of the main page https://wekan.github.io/ 

The link "Transparency" is leading to the non existing URL https://blog.wekan.team/2020/06/maximum-transparency/
"Blog" is leading to the non existing URL https://blog.wekan.team/

maybe this could be fixed.

Greetings

**Comment by xet7** [comment]
@Tanarri 

Thanks! I'll check why that website at that URL is not online, and make it online again.

**Comment by xet7** [comment]
Ok now it works.
